database:
  host: localhost
  port: 5432
  name: gnomad_db
  user: your_user
  password: your_password

paths:
  raw_data: data/raw
  processed_data: data/processed
  
gnomad:
  vcf_url: "https://gnomad.broadinstitute.org/downloads"
  version: "v2.1.1"